"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>VANTAGE CORE | Multicore Scheduler</title>\n"
"<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
"<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
"<link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@400;700&family=IBM+Plex+Mono:wght@400;600;700&display=swap\" rel=\"stylesheet\">\n"
"<style>\n"
":root{\n"
"  --bg:#0a0a0a;--surface:#121212;--carbon:#27272a;--slate:#3f3f46;\n"
"  --amber:#fbbf24;--green:#22c55e;--red:#ef4444;\n"
"  --text:#f5f5f5;--dim:#a1a1aa;--border:rgba(255,255,255,0.06);\n"
"  --r-xl:24px;--r-lg:16px;--r-md:12px;\n"
"  --font:'Outfit',sans-serif;--mono:'IBM Plex Mono',monospace;\n"
"}\n"
"*{margin:0;padding:0;box-sizing:border-box;}\n"
"body{\n"
"  background:var(--bg);color:var(--text);font-family:var(--font);\n"
"  -webkit-font-smoothing:antialiased;min-height:100vh;\n"
"  background-image:radial-gradient(circle at 50% -20%,#181818,transparent);\n"
"}\n"
".container{max-width:1440px;margin:0 auto;padding:28px 32px;}\n"
"\n"
"/* ── Header ─────────────────────────────────────────────── */\n"
"header{\n"
"  display:flex;justify-content:space-between;align-items:center;\n"
"  padding:18px 28px;background:rgba(255,255,255,0.03);\n"
"  border:1px solid var(--border);border-radius:var(--r-xl);\n"
"  margin-bottom:32px;\n"
"}\n"
".brand{display:flex;align-items:center;gap:14px;}\n"
".brand-bar{width:5px;height:24px;background:var(--amber);border-radius:4px;flex-shrink:0;}\n"
".brand h1{\n"
"  font-size:22px;font-weight:700;letter-spacing:-.02em;\n"
"  display:flex;align-items:center;gap:8px;\n"
"}\n"
".brand h1 span{color:var(--amber);}\n"
".brand p{\n"
"  font-size:10px;font-family:var(--mono);color:var(--dim);\n"
"  text-transform:uppercase;letter-spacing:.18em;margin-top:3px;opacity:.7;\n"
"}\n"
".nav-pills{display:flex;gap:8px;align-items:center;}\n"
".pill{\n"
"  display:flex;align-items:center;gap:7px;padding:7px 16px;\n"
"  background:rgba(255,255,255,0.04);border:1px solid var(--border);\n"
"  border-radius:99px;font-size:11px;font-weight:600;\n"
"  font-family:var(--mono);letter-spacing:.04em;\n"
"}\n"
".pill .gdot{\n"
"  width:7px;height:7px;border-radius:50%;background:var(--green);\n"
"  box-shadow:0 0 8px var(--green);animation:blink 2s infinite;flex-shrink:0;\n"
"}\n"
".pill.offline .gdot{background:var(--red);box-shadow:0 0 8px var(--red);}\n"
".pill .val{color:var(--amber);}\n"
"@keyframes blink{0%,100%{opacity:1}50%{opacity:.3}}\n"
".header-actions{display:flex;gap:8px;}\n"
".btn-h{\n"
"  padding:8px 18px;border-radius:99px;cursor:pointer;\n"
"  font-size:12px;font-weight:700;font-family:var(--font);\n"
"  border:1px solid var(--border);background:rgba(255,255,255,0.05);\n"
"  color:var(--text);transition:all .2s;\n"
"}\n"
".btn-h:hover{background:rgba(255,255,255,.1);}\n"
".btn-h.primary{background:var(--amber);color:#000;border:none;}\n"
".btn-h.primary:hover{background:#fcd34d;box-shadow:0 0 20px rgba(251,191,36,.25);}\n"
"/* ── Ticker ─────────────────────────────────────────────── */\n"
".ticker{font-family:var(--mono);font-size:11px;font-weight:600;\n"
"  letter-spacing:.04em;min-width:1ch;display:inline-block;\n"
"  border-right:1.5px solid var(--amber);animation:caret .7s step-end infinite;}\n"
"@keyframes caret{0%,100%{border-color:var(--amber)}50%{border-color:transparent}}\n"
"\n"
"/* ── Main layout ─────────────────────────────────────────── */\n"
".main-grid{display:grid;grid-template-columns:1fr 380px;gap:32px;}\n"
".section-head{\n"
"  display:flex;justify-content:space-between;align-items:flex-end;\n"
"  margin-bottom:24px;\n"
"}\n"
".section-title{font-size:22px;font-weight:700;letter-spacing:-.01em;}\n"
".section-sub{font-size:12px;color:var(--dim);font-family:var(--mono);margin-top:3px;}\n"
".algo-badge{\n"
"  background:var(--amber);color:#000;padding:5px 12px;\n"
"  border-radius:99px;font-size:10px;font-weight:600;font-family:var(--mono);\n"
"}\n"
"\n"
"/* ── Core grid ───────────────────────────────────────────── */\n"
".core-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:16px;}\n"
".core-card{\n"
"  background:var(--surface);border:1px solid var(--border);\n"
"  border-radius:var(--r-lg);padding:20px;\n"
"  transition:all .3s cubic-bezier(.4,0,.2,1);\n"
"}\n"
".core-card:hover{border-color:rgba(251,191,36,.3);transform:translateY(-3px);}\n"
".core-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;}\n"
".core-id{font-family:var(--mono);font-size:10px;color:var(--dim);font-weight:700;}\n"
".core-pct{font-size:18px;font-weight:700;color:var(--amber);}\n"
".prog-bg{height:5px;background:var(--carbon);border-radius:99px;overflow:hidden;margin-bottom:14px;}\n"
".prog-fill{\n"
"  height:100%;border-radius:99px;width:0%;\n"
"  background:linear-gradient(90deg,var(--amber),#f97316);\n"
"  transition:width .4s cubic-bezier(.34,1.56,.64,1);\n"
"}\n"
".core-foot{\n"
"  display:flex;justify-content:space-between;\n"
"  font-family:var(--mono);font-size:10px;color:var(--dim);font-weight:700;\n"
"  text-transform:uppercase;\n"
"}\n"
"\n"
"/* ── Perf grid ───────────────────────────────────────────── */\n"
".perf-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:24px;}\n"
".perf-card{\n"
"  background:var(--surface);border:1px solid var(--border);\n"
"  border-radius:var(--r-xl);padding:22px;text-align:center;\n"
"  transition:all .3s cubic-bezier(.4,0,.2,1);\n"
"}\n"
".perf-card:hover{border-color:rgba(251,191,36,.2);transform:translateY(-3px);}\n"
".perf-value{font-size:30px;font-weight:700;letter-spacing:-.02em;margin-bottom:5px;}\n"
".perf-label{font-size:9px;color:var(--dim);text-transform:uppercase;font-weight:800;\n"
"  letter-spacing:.12em;font-family:var(--mono);}\n"
"\n"
"/* ── Sidebar ─────────────────────────────────────────────── */\n"
".sidebar-block{margin-bottom:28px;}\n"
".card{\n"
"  background:var(--surface);border:1px solid var(--border);\n"
"  border-radius:var(--r-xl);padding:24px;\n"
"}\n"
".manifest-grid{display:grid;gap:10px;}\n"
".manifest-item{\n"
"  background:rgba(255,255,255,0.025);\n"
"  padding:12px 16px;border-radius:var(--r-md);\n"
"  border:1px solid var(--border);\n"
"}\n"
".manifest-label{\n"
"  font-size:9px;color:var(--dim);text-transform:uppercase;\n"
"  letter-spacing:.12em;font-weight:700;font-family:var(--mono);margin-bottom:5px;\n"
"}\n"
".manifest-value{\n"
"  font-size:12px;font-weight:600;\n"
"  white-space:nowrap;overflow:hidden;text-overflow:ellipsis;\n"
"}\n"
".manifest-2col{display:grid;grid-template-columns:1fr 1fr;gap:10px;}\n"
"\n"
"/* ── Control buttons ─────────────────────────────────────── */\n"
".btn-group{display:grid;gap:10px;}\n"
".btn{\n"
"  padding:14px 18px;border-radius:var(--r-md);\n"
"  font-family:var(--font);font-size:13px;font-weight:700;cursor:pointer;\n"
"  border:1px solid var(--border);background:var(--carbon);\n"
"  color:var(--text);display:flex;align-items:center;\n"
"  justify-content:space-between;transition:all .2s;\n"
"}\n"
".btn:hover{background:var(--slate);border-color:rgba(255,255,255,.14);transform:scale(1.02);}\n"
".btn.primary{background:var(--text);color:var(--bg);border:none;}\n"
".btn.primary:hover{background:#fff;box-shadow:0 0 20px rgba(255,255,255,.15);}\n"
".btn.active{border-color:var(--amber);color:var(--amber);background:rgba(251,191,36,.06);}\n"
".btn.danger{background:rgba(239,68,68,.08);color:var(--red);border-color:rgba(239,68,68,.2);}\n"
".btn.danger:hover{background:var(--red);color:#fff;}\n"
".divider{height:1px;background:rgba(255,255,255,0.05);margin:2px 0;}\n"
"\n"
"/* ── Offline ─────────────────────────────────────────────── */\n"
"#offline{\n"
"  display:none;position:fixed;top:0;left:0;right:0;\n"
"  padding:7px;background:rgba(239,68,68,.12);\n"
"  border-bottom:1px solid rgba(239,68,68,.25);\n"
"  color:var(--red);text-align:center;font-size:11px;\n"
"  font-weight:700;font-family:var(--mono);z-index:999;\n"
"}\n"
"/* ── Live stats strip in sidebar ────────────────────────── */\n"
".live-strip{\n"
"  display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:10px;\n"
"}\n"
".live-stat{\n"
"  background:rgba(255,255,255,0.025);border:1px solid var(--border);\n"
"  border-radius:var(--r-md);padding:12px 14px;\n"
"}\n"
".live-stat .ls-key{font-size:9px;color:var(--dim);text-transform:uppercase;\n"
"  letter-spacing:.12em;font-weight:700;font-family:var(--mono);margin-bottom:4px;}\n"
".live-stat .ls-val{font-size:16px;font-weight:700;color:var(--amber);}\n"
"/* ── Horizontal control rows ─────────────────────────────── */\n"
".ctrl-row{display:flex;gap:8px;margin-bottom:8px;}\n"
".ctrl-row .btn{flex:1;justify-content:center;padding:11px 10px;font-size:12px;}\n"
".ctrl-row .btn.primary{justify-content:space-between;}\n"
"/* ============================================================\n"
"   RESPONSIVE — TABLET  (≤1100px)\n"
"   ============================================================ */\n"
"@media(max-width:1100px){\n"
"  .container{padding:20px 20px;}\n"
"  .main-grid{grid-template-columns:1fr;gap:20px;}\n"
"  .perf-grid{grid-template-columns:repeat(2,1fr);gap:12px;}\n"
"  .core-grid{grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:12px;}\n"
"  header{flex-wrap:wrap;gap:12px;padding:14px 18px;}\n"
"  .header-actions{width:100%;justify-content:flex-end;display:flex;gap:8px;}\n"
"}\n"
"\n"
"/* ============================================================\n"
"   RESPONSIVE — MOBILE  (≤768px)\n"
"   ============================================================ */\n"
"@media(max-width:768px){\n"
"  .container{padding:12px;}\n"
"\n"
"  /* Header collapses to 2 rows */\n"
"  header{\n"
"    flex-direction:column;align-items:flex-start;\n"
"    gap:12px;padding:14px 16px;border-radius:16px;\n"
"    margin-bottom:16px;\n"
"  }\n"
"  .brand h1{font-size:18px;}\n"
"  .brand p{display:none;}\n"
"  .nav-pills{width:100%;flex-wrap:wrap;gap:6px;}\n"
"  .pill{padding:5px 12px;font-size:10px;}\n"
"  .header-actions{width:100%;display:flex;gap:6px;}\n"
"  .btn-h{flex:1;text-align:center;padding:8px 6px;font-size:11px;}\n"
"\n"
"  /* Layout: full single column */\n"
"  .main-grid{grid-template-columns:1fr;gap:14px;}\n"
"\n"
"  /* Cores: 2 per row on mobile */\n"
"  .core-grid{grid-template-columns:repeat(2,1fr);gap:10px;}\n"
"  .core-card{padding:14px;border-radius:12px;}\n"
"  .core-pct{font-size:15px;}\n"
"\n"
"  /* Section headers */\n"
"  .section-title{font-size:18px;}\n"
"  .section-sub{font-size:11px;}\n"
"\n"
"  /* Perf: 2x2 grid */\n"
"  .perf-grid{grid-template-columns:repeat(2,1fr);gap:10px;margin-top:14px;}\n"
"  .perf-card{padding:16px;border-radius:14px;}\n"
"  .perf-value{font-size:24px;}\n"
"\n"
"  /* Manifest: single column */\n"
"  .manifest-2col{grid-template-columns:1fr;}\n"
"  .card{padding:16px;border-radius:16px;}\n"
"\n"
"  /* Control nexus: bigger touch targets */\n"
"  .ctrl-row{flex-wrap:wrap;gap:8px;}\n"
"  .ctrl-row .btn{min-height:44px;font-size:12px;flex:1 1 auto;}\n"
"\n"
"  /* Live stats: tighter */\n"
"  .live-strip{gap:8px;}\n"
"  .live-stat{padding:10px 12px;}\n"
"  .live-stat .ls-val{font-size:14px;}\n"
"\n"
"  /* Algo badge: smaller */\n"
"  .algo-badge{font-size:9px;padding:4px 10px;}\n"
"}\n"
"\n"
"/* ============================================================\n"
"   RESPONSIVE — SMALL MOBILE  (≤480px)\n"
"   ============================================================ */\n"
"@media(max-width:480px){\n"
"  .container{padding:8px;}\n"
"\n"
"  /* Header: minimal */\n"
"  header{border-radius:12px;padding:12px;margin-bottom:10px;}\n"
"  .brand-bar{width:4px;height:18px;}\n"
"  .brand h1{font-size:16px;}\n"
"  .brand{gap:10px;}\n"
"\n"
"  /* Cores: single column on very small */\n"
"  .core-grid{grid-template-columns:1fr;}\n"
"  .core-pct{font-size:14px;}\n"
"\n"
"  /* Perf: 2x2 stays but more compact */\n"
"  .perf-value{font-size:20px;}\n"
"  .perf-label{font-size:8px;}\n"
"  .perf-card{padding:12px;}\n"
"\n"
"  /* Pills wrap tightly */\n"
"  .pill{padding:4px 10px;font-size:9px;}\n"
"  .nav-pills{gap:4px;}\n"
"\n"
"  /* Manifest compact */\n"
"  .manifest-item{padding:10px 12px;}\n"
"  .manifest-value{font-size:11px;}\n"
"\n"
"  /* Control full-width stacked */\n"
"  .ctrl-row{flex-direction:column;}\n"
"  .ctrl-row .btn{width:100%;}\n"
"\n"
"  /* Live stats: 3 col stays but minimal */\n"
"  .live-stat .ls-val{font-size:13px;}\n"
"  .live-stat .ls-key{font-size:8px;}\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div id=\"offline\">ENGINE OFFLINE &#8212; reconnecting&#8230;</div>\n"
"<div class=\"container\">\n"
"\n"
"  <header>\n"
"    <div class=\"brand\">\n"
"      <div class=\"brand-bar\"></div>\n"
"      <div>\n"
"        <h1>KRONOS <span>SCHEDULER</span></h1>\n"
"        <p>Kernel&#8209;Aware Multicore Load Balancer &mdash; Win32 Native Engine</p>\n"
"      </div>\n"
"    </div>\n"
"    <div class=\"nav-pills\">\n"
"      <div class=\"pill\" id=\"pill-status\">\n"
"        <div class=\"gdot\"></div>\n"
"        <span class=\"ticker\" id=\"ticker\"></span>\n"
"      </div>\n"
"    </div>\n"
"    <div class=\"header-actions\">\n"
"      <button class=\"btn-h\" onclick=\"runBench(10)\">+10</button>\n"
"      <button class=\"btn-h primary\" onclick=\"runBench(100)\">INJECT 100</button>\n"
"      <button class=\"btn-h\" onclick=\"runBench(1000)\">BURST 1K</button>\n"
"    </div>\n"
"  </header>\n"
"\n"
"  <div class=\"main-grid\">\n"
"\n"
"    <!-- Left: cores + perf -->\n"
"    <div>\n"
"      <div class=\"section-head\">\n"
"        <div>\n"
"          <div class=\"section-title\">Core Topology</div>\n"
"          <div class=\"section-sub\">Active task distribution across affinity-pinned logical units</div>\n"
"        </div>\n"
"        <div class=\"algo-badge\" id=\"algo-badge\">Work Stealing</div>\n"
"      </div>\n"
"      <div class=\"core-grid\" id=\"cores-grid\"></div>\n"
"      <div class=\"perf-grid\">\n"
"        <div class=\"perf-card\">\n"
"          <div class=\"perf-value\" id=\"p-total\">0</div>\n"
"          <div class=\"perf-label\">Tasks Managed</div>\n"
"        </div>\n"
"        <div class=\"perf-card\">\n"
"          <div class=\"perf-value\" id=\"p-done\" style=\"color:var(--green)\">0</div>\n"
"          <div class=\"perf-label\">Completed</div>\n"
"        </div>\n"
"        <div class=\"perf-card\">\n"
"          <div class=\"perf-value\" id=\"p-tps\" style=\"color:var(--amber)\">0.0</div>\n"
"          <div class=\"perf-label\">Tasks / Sec</div>\n"
"        </div>\n"
"        <div class=\"perf-card\">\n"
"          <div class=\"perf-value\" id=\"p-eff\" style=\"color:var(--amber)\">0%</div>\n"
"          <div class=\"perf-label\">Load Efficiency</div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <!-- Control Nexus in left column -->\n"
"      <div class=\"section-head\" style=\"margin-top:28px\">\n"
"        <div class=\"section-title\">Control Nexus</div>\n"
"      </div>\n"
"      <div class=\"card\">\n"
"        <div class=\"ctrl-row\">\n"
"          <button class=\"btn primary\" onclick=\"runBench(100)\">\n"
"            INJECT 100 TASKS\n"
"            <svg width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"><path d=\"M5 12h14m-7-7 7 7-7 7\"/></svg>\n"
"          </button>\n"
"          <button class=\"btn\" onclick=\"runBench(500)\">500 TASKS</button>\n"
"          <button class=\"btn\" onclick=\"runBench(1000)\">BURST 1K</button>\n"
"        </div>\n"
"        <div class=\"divider\"></div>\n"
"        <div class=\"ctrl-row\">\n"
"          <button class=\"btn\" id=\"btn-rr\" onclick=\"setAlgo(0)\">ROUND ROBIN</button>\n"
"          <button class=\"btn\" id=\"btn-ll\" onclick=\"setAlgo(1)\">LEAST LOADED</button>\n"
"          <button class=\"btn active\" id=\"btn-ws\" onclick=\"setAlgo(2)\">WORK STEALING</button>\n"
"        </div>\n"
"        <div class=\"divider\"></div>\n"
"        <div class=\"ctrl-row\">\n"
"          <button class=\"btn danger\" onclick=\"haltEngine()\">\n"
"            HALT ENGINE\n"
"            <svg width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M18.36 6.64a9 9 0 1 1-12.73 0\"/><line x1=\"12\" y1=\"2\" x2=\"12\" y2=\"12\"/></svg>\n"
"          </button>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Right: sidebar -->\n"
"    <div>\n"
"      <div class=\"sidebar-block\">\n"
"        <div class=\"section-head\">\n"
"          <div class=\"section-title\" style=\"font-size:18px\">System Manifest</div>\n"
"        </div>\n"
"        <div class=\"card manifest-grid\">\n"
"          <div class=\"manifest-item\">\n"
"            <div class=\"manifest-label\">Processor Unit</div>\n"
"            <div class=\"manifest-value\" id=\"m-cpu\">-</div>\n"
"          </div>\n"
"          <div class=\"manifest-item\">\n"
"            <div class=\"manifest-label\">Graphics Node</div>\n"
"            <div class=\"manifest-value\" id=\"m-gpu\">-</div>\n"
"          </div>\n"
"          <div class=\"manifest-item\">\n"
"            <div class=\"manifest-label\">Motherboard</div>\n"
"            <div class=\"manifest-value\" id=\"m-mb\">-</div>\n"
"          </div>\n"
"          <div class=\"manifest-item\">\n"
"            <div class=\"manifest-label\">OS Environment</div>\n"
"            <div class=\"manifest-value\" id=\"m-os\">-</div>\n"
"          </div>\n"
"          <div class=\"manifest-item\">\n"
"            <div class=\"manifest-label\">Storage Bus</div>\n"
"            <div class=\"manifest-value\" id=\"m-storage\">-</div>\n"
"          </div>\n"
"          <div class=\"manifest-2col\">\n"
"            <div class=\"manifest-item\">\n"
"              <div class=\"manifest-label\">Logical Units</div>\n"
"              <div class=\"manifest-value\" id=\"m-cores\">-</div>\n"
"            </div>\n"
"            <div class=\"manifest-item\">\n"
"              <div class=\"manifest-label\">System RAM</div>\n"
"              <div class=\"manifest-value\" id=\"m-mem\">-</div>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <div class=\"sidebar-block\">\n"
"        <div class=\"section-head\">\n"
"          <div class=\"section-title\" style=\"font-size:18px\">Live Stats</div>\n"
"        </div>\n"
"        <div class=\"live-strip\">\n"
"          <div class=\"live-stat\"><div class=\"ls-key\">CORES</div><div class=\"ls-val\" id=\"nav-cores\">--</div></div>\n"
"          <div class=\"live-stat\"><div class=\"ls-key\">UPTIME</div><div class=\"ls-val\" id=\"nav-up\">00:00</div></div>\n"
"          <div class=\"live-stat\"><div class=\"ls-key\">TPS</div><div class=\"ls-val\" id=\"nav-tps\">0</div></div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"    </div>\n"
"\n"
"  </div>\n"
"</div>\n"
"\n"
"<script>\n"
"'use strict';\n"
"var numCores=0, startMs=Date.now(), smooth=[];\n"
"\n"
"/* ── Kernel status ticker ──────────────────────────────── */\n"
"(function(){\n"
"  var msgs=[\n"
"    'Sched Active',\n"
"    'Affinity Locked',\n"
"    'Work Stealing',\n"
"    'Push Migration',\n"
"    'Kernel Pinned',\n"
"    'Cache Local',\n"
"    'Queue Balanced',\n"
"    'Win32 Native'\n"
"  ];\n"
"  var mi=0, ci=0, typing=true, el;\n"
"  function tick(){\n"
"    if(!el) el=document.getElementById('ticker');\n"
"    if(!el) return;\n"
"    var word=msgs[mi];\n"
"    if(typing){\n"
"      el.textContent=word.slice(0,++ci);\n"
"      if(ci>=word.length){typing=false;setTimeout(tick,1800);return;}\n"
"      setTimeout(tick,55);\n"
"    } else {\n"
"      el.textContent=word.slice(0,--ci);\n"
"      if(ci<=0){typing=true;mi=(mi+1)%msgs.length;setTimeout(tick,400);return;}\n"
"      setTimeout(tick,28);\n"
"    }\n"
"  }\n"
"  setTimeout(tick,800);\n"
"})();\n"
"\n"
"setInterval(function(){\n"
"  var s=Math.floor((Date.now()-startMs)/1000);\n"
"  var h=String(Math.floor(s/3600)).padStart(2,'0');\n"
"  var m=String(Math.floor((s%3600)/60)).padStart(2,'0');\n"
"  document.getElementById('nav-up').textContent=h+':'+m;\n"
"},1000);\n"
"\n"
"function buildGrid(n){\n"
"  var g=document.getElementById('cores-grid'); g.innerHTML='';\n"
"  for(var i=0;i<n;i++){\n"
"    smooth[i]=0;\n"
"    g.innerHTML+=\n"
"      '<div class=\"core-card\">'+\n"
"      '<div class=\"core-head\">'+\n"
"      '<span class=\"core-id\">UNIT_'+String(i).padStart(2,'0')+'</span>'+\n"
"      '<span class=\"core-pct\" id=\"cp-'+i+'\">0%</span>'+\n"
"      '</div>'+\n"
"      '<div class=\"prog-bg\"><div class=\"prog-fill\" id=\"pf-'+i+'\"></div></div>'+\n"
"      '<div class=\"core-foot\">'+\n"
"      '<span id=\"cq-'+i+'\">Q: 0</span>'+\n"
"      '<span id=\"ca-'+i+'\">A: 0</span>'+\n"
"      '</div></div>';\n"
"  }\n"
"}\n"
"\n"
"function applyCores(cores){\n"
"  for(var i=0;i<numCores;i++){\n"
"    if(!cores[i]) continue;\n"
"    var u=cores[i].usage||0;\n"
"    smooth[i]=smooth[i]*0.55+u*0.45;\n"
"    document.getElementById('cp-'+i).textContent=Math.round(smooth[i])+'%';\n"
"    document.getElementById('pf-'+i).style.width=smooth[i]+'%';\n"
"    document.getElementById('cq-'+i).textContent='Q: '+cores[i].queue;\n"
"    document.getElementById('ca-'+i).textContent='A: '+cores[i].active;\n"
"  }\n"
"}\n"
"\n"
"function connectWS(){\n"
"  var ws=new WebSocket('ws://'+location.host+'/ws');\n"
"  ws.onopen=function(){\n"
"    document.getElementById('offline').style.display='none';\n"
"    document.getElementById('pill-status').classList.remove('offline');\n"
"    document.getElementById('status-txt').textContent='SYSTEM_STABLE';\n"
"  };\n"
"  ws.onmessage=function(e){\n"
"    var d; try{d=JSON.parse(e.data);}catch(x){return;}\n"
"    document.getElementById('p-total').textContent=d.total.toLocaleString();\n"
"    document.getElementById('p-done').textContent=d.completed.toLocaleString();\n"
"    var tps=d.throughput||0;\n"
"    document.getElementById('p-tps').textContent=tps.toFixed(1);\n"
"    document.getElementById('nav-tps').textContent=tps.toFixed(1);\n"
"    document.getElementById('p-eff').textContent=Math.round(d.efficiency||0)+'%';\n"
"    if(d.cores) applyCores(d.cores);\n"
"  };\n"
"  ws.onclose=function(){\n"
"    document.getElementById('offline').style.display='block';\n"
"    document.getElementById('pill-status').classList.add('offline');\n"
"    document.getElementById('status-txt').textContent='OFFLINE';\n"
"    setTimeout(connectWS,2500);\n"
"  };\n"
"}\n"
"\n"
"function runBench(n){ fetch('/api/bench?count='+n+'&iters=5000000'); }\n"
"\n"
"function setAlgo(a){\n"
"  var labels=['Round Robin','Least Loaded','Work Stealing'];\n"
"  var ids=['btn-rr','btn-ll','btn-ws'];\n"
"  for(var i=0;i<ids.length;i++)\n"
"    document.getElementById(ids[i]).classList.toggle('active',i===a);\n"
"  document.getElementById('algo-badge').textContent=labels[a];\n"
"  fetch('/api/algo?a='+a);\n"
"}\n"
"\n"
"function haltEngine(){\n"
"  if(confirm('CONFIRM ENGINE HALT?')){\n"
"    fetch('/api/stop').then(function(){\n"
"      document.getElementById('status-txt').textContent='HALTED';\n"
"      document.getElementById('pill-status').classList.add('offline');\n"
"    });\n"
"  }\n"
"}\n"
"\n"
"window.onload=function(){\n"
"  fetch('/api/info').then(function(r){return r.json();}).then(function(d){\n"
"    numCores=d.cores;\n"
"    document.getElementById('nav-cores').textContent=d.cores;\n"
"    document.getElementById('m-cpu').textContent=d.cpu;\n"
"    document.getElementById('m-gpu').textContent=d.gpu;\n"
"    document.getElementById('m-mb').textContent=d.mb;\n"
"    document.getElementById('m-os').textContent=d.os+' ('+d.build+')';\n"
"    document.getElementById('m-storage').textContent=d.storage;\n"
"    document.getElementById('m-cores').textContent=d.cores+' Logical';\n"
"    document.getElementById('m-mem').textContent=d.memory+' MB';\n"
"    buildGrid(numCores);\n"
"    connectWS();\n"
"  });\n"
"};\n"
"</script>\n"
"</body>\n"
"</html>\n"
